version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: localhost
    ports:
      - '5673:5672'
      - '15673:15672'
    env_file:
      - .env